
target:main.o add_bgn.o add_end.o dte_bgn.o dte_end.o display.o odd.o
	$(cc) $^ -o $@
main.o:main.c
	$(cc) -c $<
add_bgn.o:add_bgn.c
	$(cc) -c $<
add_end.o:add_end.c
	$(cc) -c $<
dte_bgn.o:dte_bgn.c
	$(cc) -c $<
dte_end.o:dte_end.c
	$(cc) -c $<
display.o:display.c
	$(cc) -c $<
odd.o:odd.c
	$(cc) -c $<
clean:
	rm *.o
